server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles.include: core
  config:
    use-legacy-processing: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:public;
      username: sa
      password:
  jpa:
    open-in-view: false
    hibernate:
      show_sql: true
      format_sql: true
      inspect_stacktrace: true
      naming_physical_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  #naming.physical-strategy(변수 명과 DB칼럼명을 그대로 매핑)
      ddl-auto: create
  h2:
    console:
      enabled: true



logging:
  pattern:
    console: "* %-20(%cyan(%date{HH:mm:ss.SSS}) [%thread]) %highlight(%-5level) %magenta(%marker|%logger{36}): %msg%n%rEx" # console pattern
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor.sql.basicBinder: TRACE
          BasicTypeRegistry: WARN
        transaction.JDBCTransaction: DEBUG
        jdbc.connectionManager: DEBUG
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.springframework.boot.autoconfigure: ERROR
    org.springframework.data.repository.config: ERROR
    springfox: ERROR
    io.swagger.models.parameters.AbstractSerializableParameter: ERROR
    com.zaxxer.hikari: DEBUG