#apis
apis:
  kakao-search:
    endpoint: https://dapi.kakao.com
    host: dapi.kakao.com
    apikey: 53a071709b55ac987e4e23432bdccbe7
  naver-search:
    endpoint: https://openapi.naver.com
    client-id: 3abQ8LUJj7ZHkg_Evt0z
    client-secret: F1TSIv2T0l